title: Fills Alert Bot
description: "Alerts you on Telegram whenever your trade order gets filled/executed"
email: fills_alert@protonmail.com
url: "https://t.me/FillsAlertBot"

google_analytics: "UA-125411120-1"

github:
  is_project_page: false

bot:
  url: "tg://resolve?domain=FillsAlertBot"

theme: jekyll-theme-cayman
