title: Crypto Fills Alert Bot
description: "Alerts you on Telegram whenever your trade order gets filled/executed"
email: fills_alert@protonmail.com
url: "https://t.me/FillsAlertBot"

github:
  is_project_page: false

theme: jekyll-theme-cayman
